# Generated by Django 5.2.15 on 2026-06-18 18:01

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=datetime.time(19, 0))),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Sports', 'Sports'), ('Comedy', 'Comedy'), ('Movies', 'Movies'), ('Theatre', 'Theatre'), ('Tech', 'Tech')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(default='Bhopal', max_length=100)),
                ('venue', models.CharField(default='Main Auditorium', max_length=200)),
                ('price', models.IntegerField()),
                ('seats_available', models.PositiveIntegerField(default=100)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('language', models.CharField(default='Hindi, English', max_length=80)),
                ('duration', models.CharField(default='2h 30m', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['date', 'time', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('seats', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('total_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
    ]
