# Generated by Django 6.0.4 on 2026-04-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Sports', 'Sports'), ('Comedy', 'Comedy'), ('Tech', 'Tech')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
