# Generated by Django 6.0.4 on 2026-04-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=299),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='Bhopal', max_length=200),
        ),
    ]
