# Generated by Codex on 2026-06-15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_description_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Bhopal', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(default='2h 30m', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(default='Hindi, English', max_length=80),
        ),
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='event',
            name='seats_available',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='19:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Main Auditorium', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Sports', 'Sports'), ('Comedy', 'Comedy'), ('Movies', 'Movies'), ('Theatre', 'Theatre'), ('Tech', 'Tech')], max_length=50),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('seats', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('total_amount', models.PositiveIntegerField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
    ]
