# Generated by Codex on 2026-06-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_booking_professional_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time', 'title']},
        ),
    ]
