# Generated by Django 6.0.4 on 2026-06-15 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_booking_user_status_cancelled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
    ]
